-- Processo ETL
SELECT * FROM st_cadastro_cliente;

ALTER TABLE st_cadastro_cliente ADD (DATA_REGISTRO DATE); -- Adicionando coluna data_registro
UPDATE st_cadastro_cliente SET DATA_REGISTRO = CURRENT_DATE;  -- Adicionando a data com o update usando a função current_date
COMMIT;

UPDATE st_cadastro_cliente SET EMAIL_CLIENTE = 'nao informado' WHERE EMAIL_CLIENTE IS NULL; -- Alterando valores nulos
COMMIT;

UPDATE st_cadastro_cliente SET EMAIL_CLIENTE = 'nao informado' WHERE SUBSTR(EMAIL_CLIENTE, 1,3) = 'xxx' ;
COMMIT;

-- Criar uma função para conversão valores
CREATE FUNCTION is_numeric( p_str IN VARCHAR2 )
    RETURN NUMBER IS l_num NUMBER;
BEGIN l_num := to_number( p_str );
    RETURN 1;
EXCEPTION
    WHEN value_error
    THEN RETURN 0;
END;

UPDATE st_cadastro_cliente SET EMAIL_CLIENTE = 'nao informado' WHERE is_numeric(EMAIL_CLIENTE) = 1 ;
COMMIT;

-- Existem colunas do modelo dimensao que nao estao na tabela, vou criar uma tabela que me ajude a agrupar os dados.
CREATE TABLE ST_DIM_CLIENTE(
  NK_ID_CLIENTE VARCHAR2(20), 
  NM_CLIENTE VARCHAR2(50), 
  NM_CIDADE_CLIENTE VARCHAR2(50), 
  FLAG_ACEITA_CAMPANHA CHAR(1), 
  DESC_CEP VARCHAR2(10));

-- Adicionando os valores na tabela st_dim_cliente
INSERT INTO ST_DIM_CLIENTE
SELECT A.ID_CLIENTE, A.NOME_CLIENTE, B.CIDADE, 0 , B.CEP 
    FROM ST_CADASTRO_CLIENTE A, ST_ENDERECO B
    WHERE A.ID_CLIENTE = B.ID_CLIENTE;

SELECT * FROM ST_DIM_CLIENTE;

-- Agora irei verificar a localidade e vemos que precisamos da região 
SELECT * FROM ST_LOCALIDADE;

-- Vou criar uma tabela de apoio ST_DIM_LOCALIDADE
CREATE TABLE ST_DIM_LOCALIDADE(
    NK_ID_LOCALIDADE VARCHAR(20) NOT NULL,
    NM_LOCALIDADE VARCHAR(50) NOT NULL,
    NM_CIDADE_LOCALIDADE VARCHAR(50) NOT NULL,
    NM_REGIAO_LOCALIDADE VARCHAR(50) NOT NULL);

INSERT INTO ST_DIM_LOCALIDADE
SELECT ID_LOCALIDADE, NOME_LOCALIDADE, CIDADE_LOCALIDADE,  
CASE
WHEN CIDADE_LOCALIDADE = 'Barueri' THEN 'Sudeste'
WHEN CIDADE_LOCALIDADE = 'São Paulo' THEN 'Sudeste'
WHEN CIDADE_LOCALIDADE = 'Rio de Janeiro' THEN 'Sudeste'
WHEN CIDADE_LOCALIDADE = 'Salvador' THEN 'Nordeste'
WHEN CIDADE_LOCALIDADE = 'Tatuapé' THEN 'Sudeste'
ELSE 'NA'
END as REGIAO
FROM ST_LOCALIDADE;
COMMIT;

SELECT * FROM ST_DIM_LOCALIDADE;

-- Verificando a tabela ST_PRODUTO
SELECT * FROM ST_PRODUTO;
SELECT * FROM ST_CATEGORIA;

CREATE TABLE ST_DIM_PRODUTO (
    NK_ID_PRODUTO VARCHAR(20) NOT NULL,
    DESC_SKU VARCHAR(50) NOT NULL,
    NM_PRODUTO VARCHAR(50) NOT NULL,
    NM_CATEGORIA_PRODUTO VARCHAR(30) NOT NULL,
    NM_MARCA_PRODUTO VARCHAR(30) NOT NULL);

INSERT INTO ST_DIM_PRODUTO
SELECT A.ID_PRODUTO, A.SKU, A.NOME_PRODUTO, B.NOME_CATEGORIA,
CASE
WHEN A.NOME_PRODUTO LIKE '%Sony%' THEN 'Sony'
WHEN A.NOME_PRODUTO LIKE '%Iphone%' THEN 'Apple'
WHEN A.NOME_PRODUTO LIKE '%MSI%' THEN 'MSI'
WHEN A.NOME_PRODUTO LIKE '%Galaxy%' THEN 'Samsung'
WHEN A.NOME_PRODUTO LIKE '%ASUS%' THEN 'Asus'
WHEN A.NOME_PRODUTO LIKE '%Vaio%' THEN 'Vaio'
WHEN A.NOME_PRODUTO LIKE '%Canon%' THEN 'Canon'
ELSE 'NA'
END as MARCA_PRODUTO
FROM ST_PRODUTO A, ST_CATEGORIA B
WHERE A.ID_CATEGORIA = B.ID_CATEGORIA;
COMMIT;

SELECT * FROM ST_DIM_PRODUTO;

-- Verificando pedidos
SELECT * FROM ST_PEDIDOS
SELECT * FROM ST_ITENS_PEDIDO

CREATE TABLE ST_VENDA(
    ID_TRANSACAO INTEGER,
    DATA_VENDA DATE,
    STATUS_PAGAMENTO VARCHAR2(20),
    ID_CLIENTE INTEGER,
    ID_LOCALIDADE INTEGER,
    ID_PRODUTO INTEGER,
    QUANTIDADE INTEGER,
    PRECO_UNITARIO DECIMAL);

INSERT INTO ST_VENDA
SELECT A.ID_TRANSACAO, A.DATA_ENTREGA, 
CASE
WHEN A.STATUS_PAGAMENTO = 'NA' THEN 'Erro'
ELSE A.STATUS_PAGAMENTO
END as STATUS_PAGAMENTO, A.ID_CLIENTE, A.ID_LOCALIDADE, B.ID_PRODUTO, B.QUANTIDADE, B.PRECO_UNITARIO
FROM ST_PEDIDOS A, ST_ITENS_PEDIDO B
WHERE A.ID_TRANSACAO = B.ID_TRANSACAO;
COMMIT;

SELECT * FROM ST_VENDA
